import { AuditLogEntry } from "../types";

export const auditLog: AuditLogEntry[] = [
  { id: "log_001", action: "Approved event", actor: "Amanuel Desta", actorRole: "admin", target: "Addis Tech Summit 2026", details: "Event approved and published to platform", timestamp: "2026-05-01T09:00:00Z" },
  { id: "log_002", action: "Verified organizer", actor: "Bethlehem Girma", actorRole: "admin", target: "Addis Tech Hub", details: "Organizer verified after document review", timestamp: "2026-05-02T10:30:00Z" },
  { id: "log_003", action: "Featured event", actor: "Ephrem Teklu", actorRole: "admin", target: "Women in Tech Addis", details: "Featured event for 7 days on homepage", timestamp: "2026-05-03T11:15:00Z" },
  { id: "log_004", action: "Deactivated user", actor: "Amanuel Desta", actorRole: "admin", target: "spam_account@mail.com", details: "Account reported for suspicious activity", timestamp: "2026-05-04T08:45:00Z" },
  { id: "log_005", action: "Changed role", actor: "Bethlehem Girma", actorRole: "admin", target: "dawit@email.com", details: "Role changed from attendee to organizer", timestamp: "2026-05-05T14:00:00Z" },
  { id: "log_006", action: "Rejected event", actor: "Amanuel Desta", actorRole: "admin", target: "Unapproved Gathering", details: "Event rejected: insufficient venue details provided", timestamp: "2026-05-06T09:30:00Z" },
  { id: "log_007", action: "Removed featured", actor: "Ephrem Teklu", actorRole: "admin", target: "Ethiopian Film Festival", details: "Featured period expired after 14 days", timestamp: "2026-05-07T10:00:00Z" },
  { id: "log_008", action: "Verified organizer", actor: "Amanuel Desta", actorRole: "admin", target: "Habesha Innovators", details: "Organizer verified after business license submission", timestamp: "2026-05-08T11:30:00Z" },
  { id: "log_009", action: "Approved event", actor: "Bethlehem Girma", actorRole: "admin", target: "Ethiopian Coffee Masterclass", details: "Event approved with premium placement", timestamp: "2026-05-09T13:00:00Z" },
  { id: "log_010", action: "Featured event", actor: "Amanuel Desta", actorRole: "admin", target: "Startup Pitch Night: Bole", details: "Featured event for 14 days on homepage", timestamp: "2026-05-10T15:30:00Z" },
  { id: "log_011", action: "Deactivated user", actor: "Ephrem Teklu", actorRole: "admin", target: "fake_profile@mail.com", details: "Account deactivated: multiple fake event registrations", timestamp: "2026-05-11T09:15:00Z" },
  { id: "log_012", action: "Changed role", actor: "Bethlehem Girma", actorRole: "admin", target: "kidus.y@email.com", details: "Role changed from attendee to organizer", timestamp: "2026-05-12T10:45:00Z" },
  { id: "log_013", action: "Approved event", actor: "Ephrem Teklu", actorRole: "admin", target: "AI & Machine Learning Conference", details: "Event approved after content review", timestamp: "2026-05-13T14:00:00Z" },
  { id: "log_014", action: "Verified organizer", actor: "Amanuel Desta", actorRole: "admin", target: "Women in Tech Ethiopia", details: "Organizer verified - nonprofit status confirmed", timestamp: "2026-05-14T11:00:00Z" },
  { id: "log_015", action: "Rejected event", actor: "Bethlehem Girma", actorRole: "admin", target: "Unverified Meetup", details: "Event rejected: organizer not yet verified", timestamp: "2026-05-15T08:30:00Z" },
  { id: "log_016", action: "Featured event", actor: "Amanuel Desta", actorRole: "admin", target: "Addis Tech Summit 2026", details: "Featured event for 30 days (premium)", timestamp: "2026-05-16T09:00:00Z" },
  { id: "log_017", action: "Deactivated user", actor: "Ephrem Teklu", actorRole: "admin", target: "troll_account@mail.com", details: "Account deactivated: inappropriate behavior on platform", timestamp: "2026-05-17T16:00:00Z" },
  { id: "log_018", action: "Approved event", actor: "Bethlehem Girma", actorRole: "admin", target: "Blockchain & Finance Forum", details: "Event approved for July schedule", timestamp: "2026-05-18T10:30:00Z" },
  { id: "log_019", action: "Verified organizer", actor: "Amanuel Desta", actorRole: "admin", target: "Ethiopian Business Forum", details: "Organizer reverified after profile update", timestamp: "2026-05-19T13:45:00Z" },
  { id: "log_020", action: "Changed role", actor: "Ephrem Teklu", actorRole: "admin", target: "amanuel.d@email.com", details: "Role changed from organizer to admin", timestamp: "2026-05-20T11:15:00Z" },
  { id: "log_021", action: "Removed featured", actor: "Amanuel Desta", actorRole: "admin", target: "Meskel Square Art Walk", details: "Featured period ended - 7 day duration", timestamp: "2026-05-21T09:00:00Z" },
  { id: "log_022", action: "Approved event", actor: "Bethlehem Girma", actorRole: "admin", target: "Sustainable Business Summit", details: "Event approved for July 12 schedule", timestamp: "2026-05-22T14:30:00Z" },
  { id: "log_023", action: "Rejected event", actor: "Ephrem Teklu", actorRole: "admin", target: "Invalid Workshop", details: "Event rejected: incomplete information", timestamp: "2026-05-23T10:00:00Z" },
  { id: "log_024", action: "Featured event", actor: "Amanuel Desta", actorRole: "admin", target: "Ethiopian Coffee Masterclass", details: "Featured event for 7 days", timestamp: "2026-05-24T12:00:00Z" },
  { id: "log_025", action: "Deactivated user", actor: "Bethlehem Girma", actorRole: "admin", target: "inactive_user@mail.com", details: "Account deactivated due to 6 months inactivity", timestamp: "2026-05-25T15:00:00Z" },
  { id: "log_026", action: "Verified organizer", actor: "Ephrem Teklu", actorRole: "admin", target: "Jazzamba Events", details: "Organizer verified - music license confirmed", timestamp: "2026-05-26T11:30:00Z" },
];
