import { Event } from "../types";
import { categories } from "./categories";
import { organizers } from "./organizers";

const now = "2026-05-14T18:02:50+03:00";

export const events: Event[] = [
  {
    id: "evt_001",
    slug: "addis-tech-summit-2026",
    title: "Addis Tech Summit 2026",
    description:
      "<p>Addis Tech Summit 2026 is the premier technology conference in Ethiopia, bringing together innovators, developers, entrepreneurs, and thought leaders from across Africa and the globe. Held at the iconic Millennium Hall in Bole, this year's summit features groundbreaking keynotes from industry pioneers, hands-on workshops, and an exhibition floor showcasing the latest in AI, fintech, cloud computing, and sustainable tech solutions.</p><p>Over 2,000 attendees are expected to converge for two days of intensive learning, networking, and collaboration. The summit includes dedicated tracks for software engineering, data science, cybersecurity, and digital transformation, ensuring there is something for every tech professional regardless of their specialization.</p><p>Attendees will have the opportunity to participate in interactive panel discussions, pitch sessions for early-stage startups, and exclusive networking receptions. Industry leaders from companies like Safaricom, Ethio Telecom, and global tech giants will share insights on the future of technology in East Africa.</p><p>Whether you are a seasoned developer, a startup founder, or a tech enthusiast, Addis Tech Summit 2026 offers an unparalleled platform to learn, connect, and shape the future of technology in Ethiopia.</p>",
    shortDescription:
      "Ethiopia's largest technology conference featuring keynotes, workshops, and networking with 2,000+ innovators and industry leaders.",
    category: categories[0],
    type: "conference",
    status: "approved",
    date: "2026-06-15T00:00:00+03:00",
    endDate: "2026-06-16T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "6:00 PM",
    location: "Millennium Hall",
    address: "Bole Road, near Bole International Airport, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.02, lng: 38.77 },
    bannerImage:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517245385279-89a33b0d3f0f?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505375081540-2a25c2d9d1e4?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[0],
    ticketTiers: [
      {
        id: "tier_001",
        name: "General Admission",
        price: 500,
        currency: "ETB",
        capacity: 1500,
        sold: 420,
        description: "Full access to all keynotes, workshops, and exhibition floor.",
      },
      {
        id: "tier_002",
        name: "VIP Pass",
        price: 1500,
        currency: "ETB",
        capacity: 200,
        sold: 85,
        description: "VIP seating, exclusive networking reception, and swag bag.",
      },
      {
        id: "tier_003",
        name: "Student Pass",
        price: 200,
        currency: "ETB",
        capacity: 300,
        sold: 110,
        description: "Discounted access for students with valid ID.",
      },
    ],
    ticketType: "paid",
    tags: ["tech", "conference", "innovation", "AI", "startups"],
    isFeatured: true,
    views: 3200,
    registrations: 615,
    capacity: 2000,
    createdAt: "2026-01-10T10:00:00+03:00",
  },
  {
    id: "evt_002",
    slug: "ethiopian-coffee-masterclass",
    title: "Ethiopian Coffee Masterclass",
    description:
      "<p>Dive deep into the rich traditions and modern techniques of Ethiopian coffee at the Ethiopian Coffee Masterclass, hosted at the historic Tomoca Heritage venue in Arada. This immersive workshop takes participants on a journey from bean to cup, exploring the origins, cultivation, roasting, and brewing methods that make Ethiopian coffee world-renowned.</p><p>Led by master roasters and baristas from Addis Ababa's finest coffee houses, the masterclass covers cupping sessions, manual brewing techniques, latte art, and the cultural significance of the coffee ceremony in Ethiopian society. Participants will taste rare single-origin beans from Yirgacheffe, Sidama, and Guji regions.</p><p>The workshop is designed for both coffee enthusiasts and aspiring professionals. Each attendee receives a curated coffee kit to take home, including specialty beans and brewing tools. Small class sizes ensure personalized attention and hands-on practice throughout the session.</p><p>By the end of this masterclass, you will have a profound appreciation for Ethiopian coffee and the skills to brew exceptional cups at home or in a professional setting.</p>",
    shortDescription:
      "An immersive workshop exploring Ethiopian coffee traditions, roasting, and brewing techniques at Tomoca Heritage.",
    category: categories[6],
    type: "workshop",
    status: "approved",
    date: "2026-06-08T00:00:00+03:00",
    endDate: "2026-06-09T00:00:00+03:00",
    time: "10:00 AM",
    endTime: "4:00 PM",
    location: "Tomoca Heritage",
    address: "Wavell Street, Arada District, Addis Ababa",
    subCity: "Arada",
    coordinates: { lat: 9.04, lng: 38.74 },
    bannerImage:
      "https://images.unsplash.com/photo-1414239778000-5d3b9c3a5b3f?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1504672446908-7d8e5c1b3b2b?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556909111-44e7e7a4b1b2?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505253049-5f0d9b2f6c1a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[1],
    ticketTiers: [
      {
        id: "tier_004",
        name: "Standard Ticket",
        price: 800,
        currency: "ETB",
        capacity: 30,
        sold: 18,
        description: "Full-day masterclass with cupping session and coffee kit.",
      },
      {
        id: "tier_005",
        name: "Premium Ticket",
        price: 1500,
        currency: "ETB",
        capacity: 15,
        sold: 8,
        description: "Premium seating, signed coffee kit, and lunch at a top Addis café.",
      },
    ],
    ticketType: "paid",
    tags: ["coffee", "workshop", "Ethiopian", "culinary", "culture"],
    isFeatured: true,
    views: 2800,
    registrations: 26,
    capacity: 45,
    createdAt: "2026-02-20T09:00:00+03:00",
  },
  {
    id: "evt_003",
    slug: "startup-pitch-night-bole",
    title: "Startup Pitch Night: Bole",
    description:
      "<p>Startup Pitch Night: Bole is Addis Ababa's premier networking and pitching event for early-stage entrepreneurs and investors. Held at the vibrant Ice Addis venue in the heart of Bole, this monthly gathering provides founders with a platform to present their ventures to a curated audience of angel investors, venture capitalists, and fellow entrepreneurs.</p><p>Each event features 8-10 carefully selected startups pitching their ideas in a fast-paced format, followed by constructive feedback from a panel of experienced judges. Beyond the pitches, the evening is designed for meaningful connections over drinks and appetizers in a relaxed, high-energy atmosphere.</p><p>Previous pitch nights have led to successful funding rounds, strategic partnerships, and valuable mentorship relationships. Whether you are looking to raise capital, find a co-founder, or simply explore the startup ecosystem, Startup Pitch Night offers an invaluable gateway into Addis Ababa's growing entrepreneurial community.</p><p>The event concludes with an open networking session where attendees can connect directly with founders, investors, and ecosystem enablers. Winners receive mentorship packages and introductions to our network of partner investors.</p>",
    shortDescription:
      "A dynamic startup pitching event connecting early-stage founders with investors and the entrepreneurial community in Bole.",
    category: categories[1],
    type: "networking",
    status: "approved",
    date: "2026-06-20T00:00:00+03:00",
    endDate: "2026-06-21T00:00:00+03:00",
    time: "6:00 PM",
    endTime: "10:00 PM",
    location: "Ice Addis",
    address: "Bole Sub-city, near Dembel City Center, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.018, lng: 38.768 },
    bannerImage:
      "https://images.unsplash.com/photo-1556765909-7e9c2e9b8c1b?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559131497-34a8a3f8b1b2?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600880292289-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[2],
    ticketTiers: [
      {
        id: "tier_006",
        name: "Free Entry",
        price: 0,
        currency: "ETB",
        capacity: 150,
        sold: 65,
        description: "General admission with access to pitches and networking.",
      },
    ],
    ticketType: "free",
    tags: ["startups", "pitching", "networking", "entrepreneurship", "investment"],
    isFeatured: true,
    views: 1800,
    registrations: 65,
    capacity: 150,
    createdAt: "2026-03-01T14:00:00+03:00",
  },
  {
    id: "evt_004",
    slug: "meskel-square-art-walk",
    title: "Meskel Square Art Walk",
    description:
      "<p>The Meskel Square Art Walk transforms one of Addis Ababa's most iconic public spaces into an open-air gallery celebrating contemporary Ethiopian art. This free exhibition brings together over 50 local artists showcasing paintings, sculptures, photography, mixed media, and installations across the expansive Meskel Square in Lideta.</p><p>Curated by the Meskel Cultural Foundation, the Art Walk offers visitors a unique opportunity to experience the vibrancy of Ethiopia's contemporary art scene in a dynamic public setting. Artists will be present at their installations to discuss their work, techniques, and inspirations, making this an interactive and educational experience for all ages.</p><p>The event also features live painting demonstrations, children's art workshops, and a pop-up market where attendees can purchase original artworks directly from the creators. Food trucks and coffee stalls will be stationed around the square, creating a festive atmosphere throughout the day.</p><p>Meskel Square Art Walk is more than an exhibition—it is a celebration of Addis Ababa's creative spirit and a testament to the power of public art to bring communities together.</p>",
    shortDescription:
      "An open-air art exhibition at Meskel Square featuring 50+ Ethiopian artists with live demonstrations and workshops.",
    category: categories[2],
    type: "exhibition",
    status: "approved",
    date: "2026-06-12T00:00:00+03:00",
    endDate: "2026-06-13T00:00:00+03:00",
    time: "10:00 AM",
    endTime: "8:00 PM",
    location: "Meskel Square",
    address: "Meskel Square, Lideta Sub-city, Addis Ababa",
    subCity: "Lideta",
    coordinates: { lat: 9.01, lng: 38.73 },
    bannerImage:
      "https://images.unsplash.com/photo-1460664377893-9b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1513364776144-7b8b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1531912383-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1499898847-4b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[3],
    ticketTiers: [
      {
        id: "tier_007",
        name: "Free Entry",
        price: 0,
        currency: "ETB",
        capacity: 5000,
        sold: 0,
        description: "Free public access to all exhibitions and activities.",
      },
    ],
    ticketType: "free",
    tags: ["art", "exhibition", "culture", "Ethiopian", "public"],
    isFeatured: true,
    views: 1500,
    registrations: 0,
    capacity: 5000,
    createdAt: "2026-03-15T11:00:00+03:00",
  },
  {
    id: "evt_005",
    slug: "women-in-tech-addis",
    title: "Women in Tech Addis",
    description:
      "<p>Women in Tech Addis is a transformative meetup dedicated to empowering women in Ethiopia's technology sector. Held at the luxurious Hyatt Regency in Bole, this event brings together female engineers, developers, product managers, data scientists, and tech executives for a day of inspiration, skill-building, and community building.</p><p>The program features keynote speeches from prominent women leaders in Ethiopian tech, followed by breakout sessions covering career development, technical skill advancement, leadership, and work-life integration. Attendees will have the opportunity to participate in hands-on coding workshops, mentorship speed-dating, and panel discussions addressing the unique challenges women face in the industry.</p><p>Networking is a core component of the event, with structured opportunities for attendees to connect with peers, mentors, and potential employers. The meetup also showcases success stories of Ethiopian women who have built thriving careers in tech, both locally and internationally.</p><p>Allies and advocates are welcome. Women in Tech Addis is committed to creating an inclusive environment where everyone can contribute to building a more diverse and equitable tech ecosystem in Ethiopia.</p>",
    shortDescription:
      "A meetup empowering women in Ethiopia's tech sector with keynotes, workshops, mentorship, and networking.",
    category: categories[0],
    type: "meetup",
    status: "approved",
    date: "2026-06-25T00:00:00+03:00",
    endDate: "2026-06-26T00:00:00+03:00",
    time: "8:30 AM",
    endTime: "5:00 PM",
    location: "Hyatt Regency",
    address: "Meskel Flower Road, Bole, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.022, lng: 38.772 },
    bannerImage:
      "https://images.unsplash.com/photo-1517245385279-89a33b0d3f0f?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505375081540-2a25c2d9d1e4?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[4],
    ticketTiers: [
      {
        id: "tier_008",
        name: "Free Admission",
        price: 0,
        currency: "ETB",
        capacity: 300,
        sold: 142,
        description: "Full-day access to all sessions, workshops, and networking.",
      },
    ],
    ticketType: "free",
    tags: ["women in tech", "diversity", "mentorship", "technology", "empowerment"],
    isFeatured: true,
    views: 2400,
    registrations: 142,
    capacity: 300,
    createdAt: "2026-04-01T08:00:00+03:00",
  },
  {
    id: "evt_006",
    slug: "jazz-night-at-jazzamba",
    title: "Jazz Night at Jazzamba",
    description:
      "<p>Experience an unforgettable evening of live jazz at Jazzamba Lounge, Addis Ababa's premier jazz venue located in the heart of Bole. Jazz Night at Jazzamba features performances from Ethiopia's most acclaimed jazz musicians, blending traditional Ethiopian scales and rhythms with classic and contemporary jazz standards.</p><p>The lineup includes the legendary Alemayehu Fanta Quartet, rising star vocalist Selam Tilahun, and a special collaboration with international guest artists. The intimate setting of Jazzamba Lounge provides superb acoustics and a cozy atmosphere, making every performance feel personal and immersive.</p><p>Guests can enjoy a curated selection of Ethiopian wines, imported spirits, and signature cocktails alongside light bites from the lounge's kitchen. The evening begins with a smooth set from the house band, building toward an electrifying finale that showcases the improvisational brilliance of Ethiopian jazz.</p><p>Whether you are a lifelong jazz enthusiast or new to the genre, Jazz Night at Jazzamba promises a soul-stirring musical journey through the rich tapestry of Ethiopian and global jazz traditions.</p>",
    shortDescription:
      "An evening of live jazz at Jazzamba Lounge featuring top Ethiopian musicians in an intimate Bole setting.",
    category: categories[5],
    type: "concert",
    status: "approved",
    date: "2026-06-05T00:00:00+03:00",
    endDate: "2026-06-06T00:00:00+03:00",
    time: "7:00 PM",
    endTime: "11:30 PM",
    location: "Jazzamba Lounge",
    address: "Bole Sub-city, behind Dembel City Center, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.019, lng: 38.766 },
    bannerImage:
      "https://images.unsplash.com/photo-1493221031-3b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1511678652744-4b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1492680515-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1516450360-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[5],
    ticketTiers: [
      {
        id: "tier_009",
        name: "General Admission",
        price: 350,
        currency: "ETB",
        capacity: 120,
        sold: 78,
        description: "Standard seating with full access to the show.",
      },
      {
        id: "tier_010",
        name: "VIP Table (2 pax)",
        price: 1200,
        currency: "ETB",
        capacity: 30,
        sold: 18,
        description: "Premium table for two with bottle service and welcome drink.",
      },
    ],
    ticketType: "paid",
    tags: ["jazz", "live music", "concert", "nightlife", "Ethiopian music"],
    isFeatured: false,
    views: 1200,
    registrations: 96,
    capacity: 150,
    createdAt: "2026-04-10T15:00:00+03:00",
  },
  {
    id: "evt_007",
    slug: "blockchain-and-finance-forum",
    title: "Blockchain & Finance Forum",
    description:
      "<p>The Blockchain & Finance Forum at Sheraton Addis brings together financial industry leaders, blockchain developers, regulators, and academics to explore the transformative potential of distributed ledger technology in Ethiopia's financial sector. As the country explores digital financial inclusion and CBDC initiatives, this forum provides a critical platform for dialogue and knowledge exchange.</p><p>The agenda covers topics including decentralized finance, digital identity, cross-border payments, smart contracts, regulatory frameworks, and the role of blockchain in supporting Ethiopia's digital economy ambitions. International experts from Kenya, Nigeria, Singapore, and Switzerland will share case studies and lessons learned from their markets.</p><p>Interactive workshops will allow participants to explore real-world blockchain applications, from supply chain finance to remittances and land registry. The forum also features a startup showcase where Ethiopian blockchain ventures can demonstrate their solutions to potential investors and partners.</p><p>Networking breaks and a closing reception provide ample opportunity for attendees to build relationships with peers across the financial and technology sectors, fostering collaboration that extends beyond the forum.</p>",
    shortDescription:
      "A forum exploring blockchain technology's impact on finance, featuring experts, workshops, and a startup showcase.",
    category: categories[1],
    type: "seminar",
    status: "approved",
    date: "2026-07-03T00:00:00+03:00",
    endDate: "2026-07-04T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:30 PM",
    location: "Sheraton Addis",
    address: "Taitu Street, Bole, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.024, lng: 38.775 },
    bannerImage:
      "https://images.unsplash.com/photo-1664575198308-9b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1556765909-7e9c2e9b8c1b?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600880292289-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[6],
    ticketTiers: [
      {
        id: "tier_011",
        name: "Standard Pass",
        price: 600,
        currency: "ETB",
        capacity: 300,
        sold: 95,
        description: "Full access to all sessions, workshops, and networking events.",
      },
      {
        id: "tier_012",
        name: "Premium Pass",
        price: 2000,
        currency: "ETB",
        capacity: 80,
        sold: 34,
        description: "Premium seating, exclusive networking dinner, and speaker meet-and-greet.",
      },
    ],
    ticketType: "paid",
    tags: ["blockchain", "finance", "fintech", "regulation", "digital currency"],
    isFeatured: false,
    views: 900,
    registrations: 129,
    capacity: 380,
    createdAt: "2026-04-15T10:00:00+03:00",
  },
  {
    id: "evt_008",
    slug: "youth-entrepreneurship-workshop",
    title: "Youth Entrepreneurship Workshop",
    description:
      "<p>The Youth Entrepreneurship Workshop at UNECA Center in Kirkos is a free, high-impact training program designed for young Ethiopians aged 18-35 who aspire to start and grow their own businesses. This intensive one-day workshop covers the essential skills needed to navigate the entrepreneurial journey in Ethiopia's unique business landscape.</p><p>Facilitated by successful entrepreneurs, business coaches, and industry experts, the curriculum includes business model canvas development, financial literacy, marketing strategies for the Ethiopian market, legal considerations for startups, and access to funding opportunities. Participants work in small groups to develop and pitch their business ideas.</p><p>The workshop emphasizes practical, actionable knowledge. Each participant receives a workbook with templates, tools, and resources to continue their entrepreneurial development after the event. Selected participants will be eligible for follow-up mentorship and incubation support from partner organizations.</p><p>Special focus is given to youth-led ventures in agriculture technology, renewable energy, digital services, and creative industries—sectors with high growth potential in Ethiopia's economy.</p>",
    shortDescription:
      "A free workshop equipping young Ethiopians with practical skills to start and grow their own businesses.",
    category: categories[4],
    type: "training",
    status: "pending",
    date: "2026-06-18T00:00:00+03:00",
    endDate: "2026-06-19T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:00 PM",
    location: "UNECA Center",
    address: "Menelik II Avenue, Kirkos Sub-city, Addis Ababa",
    subCity: "Kirkos",
    coordinates: { lat: 9.02, lng: 38.75 },
    bannerImage:
      "https://images.unsplash.com/photo-1524175606-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1523242940-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1503676268-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529390078-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[7],
    ticketTiers: [
      {
        id: "tier_013",
        name: "Free Participant",
        price: 0,
        currency: "ETB",
        capacity: 100,
        sold: 55,
        description: "Free full-day workshop including materials and certificate.",
      },
    ],
    ticketType: "free",
    tags: ["entrepreneurship", "youth", "training", "business", "mentorship"],
    isFeatured: false,
    views: 2100,
    registrations: 55,
    capacity: 100,
    createdAt: "2026-04-20T09:00:00+03:00",
  },
  {
    id: "evt_009",
    slug: "addis-yoga-and-meditation-retreat",
    title: "Addis Yoga & Meditation Retreat",
    description:
      "<p>Escape the hustle of the city and rejuvenate your mind, body, and spirit at the Addis Yoga & Meditation Retreat, set against the serene backdrop of Yeka Hills Resort. This two-day retreat offers a comprehensive wellness experience combining yoga, guided meditation, breathwork, and mindfulness practices suitable for all levels from beginners to experienced practitioners.</p><p>The program is led by certified international and Ethiopian instructors who bring a blend of traditional yogic philosophy and modern wellness science. Morning sessions focus on energizing vinyasa flows and pranayama, while afternoon workshops delve into meditation techniques, stress management, and holistic health practices.</p><p>Accommodation at Yeka Hills Resort features comfortable rooms with panoramic views of the Entoto Mountains. All meals are prepared using fresh, organic ingredients, with options for vegetarian, vegan, and traditional Ethiopian dishes. The retreat also includes nature walks, journaling sessions, and a sound bath healing ceremony.</p><p>Leave the retreat feeling refreshed, centered, and equipped with practical tools to maintain your wellness practice long after you return to daily life.</p>",
    shortDescription:
      "A rejuvenating two-day wellness retreat with yoga, meditation, and mindfulness at Yeka Hills Resort.",
    category: categories[3],
    type: "workshop",
    status: "approved",
    date: "2026-06-22T00:00:00+03:00",
    endDate: "2026-06-23T00:00:00+03:00",
    time: "7:00 AM",
    endTime: "6:00 PM",
    location: "Yeka Hills Resort",
    address: "Yeka Sub-city, Entoto Mountain Foothills, Addis Ababa",
    subCity: "Yeka",
    coordinates: { lat: 9.04, lng: 38.79 },
    bannerImage:
      "https://images.unsplash.com/photo-1544367567-9b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1518616255-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545205597-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545383165-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[8],
    ticketTiers: [
      {
        id: "tier_014",
        name: "Day Pass",
        price: 500,
        currency: "ETB",
        capacity: 40,
        sold: 15,
        description: "Access to all sessions and meals for one day.",
      },
      {
        id: "tier_015",
        name: "Full Retreat Pass",
        price: 2500,
        currency: "ETB",
        capacity: 30,
        sold: 12,
        description: "Two-day full retreat including accommodation, all meals, and sessions.",
      },
    ],
    ticketType: "paid",
    tags: ["yoga", "meditation", "wellness", "retreat", "mindfulness"],
    isFeatured: false,
    views: 1600,
    registrations: 27,
    capacity: 70,
    createdAt: "2026-04-25T12:00:00+03:00",
  },
  {
    id: "evt_010",
    slug: "ethiopian-film-festival-2026",
    title: "Ethiopian Film Festival 2026",
    description:
      "<p>The Ethiopian Film Festival 2026 returns to the historic National Theatre in Arada, showcasing the best of contemporary Ethiopian cinema over four days. This year's festival features over 40 films including feature-length dramas, documentaries, short films, and animated works from emerging and established Ethiopian filmmakers both at home and in the diaspora.</p><p>The festival program includes competitive screenings judged by an international panel, director Q&A sessions, masterclasses on screenwriting and cinematography, and networking receptions for industry professionals. Special tributes will honor pioneering figures in Ethiopian cinema whose work has shaped the industry over the past five decades.</p><p>A new addition this year is the Diaspora Showcase, highlighting films produced by the Ethiopian diaspora in the United States, Europe, and the Middle East that explore themes of identity, belonging, and transnational experience. The Youth Filmmaker Competition offers a platform for young directors under 25 to present their visions.</p><p>The Ethiopian Film Festival is more than a screening event—it is a vital platform for cultural expression, industry development, and the celebration of Ethiopia's rich storytelling traditions translated through the lens of modern cinema.</p>",
    shortDescription:
      "A four-day festival showcasing 40+ Ethiopian films with screenings, masterclasses, and industry networking.",
    category: categories[2],
    type: "exhibition",
    status: "approved",
    date: "2026-07-10T00:00:00+03:00",
    endDate: "2026-07-14T00:00:00+03:00",
    time: "10:00 AM",
    endTime: "10:00 PM",
    location: "National Theatre",
    address: "Arada Sub-city, Churchill Avenue, Addis Ababa",
    subCity: "Arada",
    coordinates: { lat: 9.038, lng: 38.742 },
    bannerImage:
      "https://images.unsplash.com/photo-1513364776144-7b8b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1531912383-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1499898847-4b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1460664377893-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[9],
    ticketTiers: [
      {
        id: "tier_016",
        name: "Day Pass",
        price: 300,
        currency: "ETB",
        capacity: 300,
        sold: 88,
        description: "Access to all screenings and events on a single day.",
      },
      {
        id: "tier_017",
        name: "Festival Pass",
        price: 800,
        currency: "ETB",
        capacity: 200,
        sold: 52,
        description: "Full access to all screenings, masterclasses, and networking events across all days.",
      },
      {
        id: "tier_018",
        name: "VIP Pass",
        price: 2500,
        currency: "ETB",
        capacity: 50,
        sold: 18,
        description: "VIP seating, exclusive filmmaker reception, and festival swag bag.",
      },
    ],
    ticketType: "paid",
    tags: ["film", "cinema", "festival", "Ethiopian", "culture"],
    isFeatured: false,
    views: 3500,
    registrations: 158,
    capacity: 550,
    createdAt: "2026-05-01T09:00:00+03:00",
  },
  {
    id: "evt_011",
    slug: "cloud-computing-bootcamp",
    title: "Cloud Computing Bootcamp",
    description:
      "<p>The Cloud Computing Bootcamp at Addis ICT Village in Bole is an intensive hands-on training program designed for IT professionals and developers who want to master cloud technologies. Over three days, participants will gain practical experience with AWS, Microsoft Azure, and Google Cloud Platform through guided labs, real-world projects, and certification preparation.</p><p>The curriculum covers cloud architecture design, infrastructure as code, containerization with Docker and Kubernetes, serverless computing, cloud security best practices, and cost optimization strategies. Each module includes live demonstrations followed by hands-on exercises where participants deploy and manage cloud resources.</p><p>Instructors are certified cloud architects with experience deploying enterprise-scale solutions in the African market. The bootcamp emphasizes practical skills that participants can immediately apply in their workplaces, with case studies drawn from Ethiopian and East African organizations that have successfully migrated to the cloud.</p><p>Upon completion, participants will receive a certificate of achievement and access to post-bootcamp resources including study groups, practice exams for AWS/Azure certifications, and an alumni network for ongoing professional support.</p>",
    shortDescription:
      "An intensive three-day bootcamp covering AWS, Azure, and GCP with hands-on labs and certification prep.",
    category: categories[0],
    type: "training",
    status: "approved",
    date: "2026-06-28T00:00:00+03:00",
    endDate: "2026-06-30T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:00 PM",
    location: "Addis ICT Village",
    address: "Bole Sub-city, near Bole International Airport, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.025, lng: 38.78 },
    bannerImage:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1517245385279-89a33b0d3f0f?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505375081540-2a25c2d9d1e4?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[0],
    ticketTiers: [
      {
        id: "tier_019",
        name: "Standard Registration",
        price: 1200,
        currency: "ETB",
        capacity: 50,
        sold: 22,
        description: "Full three-day bootcamp with labs, materials, and certificate.",
      },
      {
        id: "tier_020",
        name: "Premium Registration",
        price: 2500,
        currency: "ETB",
        capacity: 20,
        sold: 8,
        description: "Includes exam voucher, one-on-one mentoring session, and premium materials.",
      },
    ],
    ticketType: "paid",
    tags: ["cloud computing", "AWS", "Azure", "GCP", "bootcamp"],
    isFeatured: false,
    views: 1100,
    registrations: 30,
    capacity: 70,
    createdAt: "2026-05-02T11:00:00+03:00",
  },
  {
    id: "evt_012",
    slug: "addis-food-festival",
    title: "Addis Food Festival",
    description:
      "<p>The Addis Food Festival returns to Friendship Park in Bole, transforming the city's beloved green space into a culinary paradise celebrating the rich diversity of Ethiopian cuisine alongside international flavors. This free family-friendly event features over 60 food vendors, live cooking demonstrations, and a vibrant atmosphere perfect for food lovers of all ages.</p><p>Visitors can sample traditional dishes from every region of Ethiopia—from the spicy stews of the north to the mild, plant-based specialties of the south—as well as curated selections of Italian, Indian, Middle Eastern, and fusion cuisines. Live cooking stages host renowned Ethiopian chefs demonstrating injera-making, coffee ceremonies, and modern takes on classic dishes.</p><p>The festival also features a craft beverage section with Ethiopian wines, craft beers from local breweries, and artisanal spirits. Cooking competitions, a kids' zone with food-themed activities, and live music performances throughout the day ensure non-stop entertainment for the whole family.</p><p>Beyond the feast, the Addis Food Festival promotes Ethiopia's culinary heritage as a driver of tourism and economic opportunity, connecting food entrepreneurs with new customers and collaborators.</p>",
    shortDescription:
      "A free food festival at Friendship Park with 60+ vendors, cooking demos, and live music celebrating Ethiopian cuisine.",
    category: categories[6],
    type: "exhibition",
    status: "approved",
    date: "2026-07-05T00:00:00+03:00",
    endDate: "2026-07-06T00:00:00+03:00",
    time: "11:00 AM",
    endTime: "9:00 PM",
    location: "Friendship Park",
    address: "Bole Sub-city, Wanza Street, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.02, lng: 38.769 },
    bannerImage:
      "https://images.unsplash.com/photo-1556909111-44e7e7a4b1b2?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1414239778000-5d3b9c3a5b3f?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1504672446908-7d8e5c1b3b2b?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505253049-5f0d9b2f6c1a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[1],
    ticketTiers: [
      {
        id: "tier_021",
        name: "Free Entry",
        price: 0,
        currency: "ETB",
        capacity: 10000,
        sold: 0,
        description: "Free public access to all food stalls, demos, and entertainment.",
      },
    ],
    ticketType: "free",
    tags: ["food", "festival", "Ethiopian cuisine", "family", "culture"],
    isFeatured: false,
    views: 4500,
    registrations: 0,
    capacity: 10000,
    createdAt: "2026-05-03T10:00:00+03:00",
  },
  {
    id: "evt_013",
    slug: "digital-marketing-masterclass",
    title: "Digital Marketing Masterclass",
    description:
      "<p>The Digital Marketing Masterclass at Capital Hotel in Bole is a comprehensive training program designed for business owners, marketing professionals, and entrepreneurs who want to master the digital channels that drive growth in today's competitive landscape. This full-day intensive covers strategy, execution, and measurement across all major digital platforms.</p><p>The curriculum includes search engine optimization, pay-per-click advertising, social media marketing, content marketing, email automation, and analytics. Participants will learn how to build a digital marketing strategy from the ground up, optimize campaigns for the Ethiopian market, and use data to continuously improve performance.</p><p>The masterclass is led by practitioners with experience managing campaigns for leading Ethiopian brands and international clients. Real case studies from the Ethiopian market illustrate what works and what does not, with actionable takeaways that participants can implement immediately after the session.</p><p>Each attendee receives a digital marketing playbook, templates for campaign planning and reporting, and access to an online community for ongoing support and knowledge sharing with fellow participants.</p>",
    shortDescription:
      "A full-day masterclass covering SEO, paid ads, social media, and analytics for the Ethiopian market.",
    category: categories[4],
    type: "workshop",
    status: "approved",
    date: "2026-06-30T00:00:00+03:00",
    endDate: "2026-07-01T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:00 PM",
    location: "Capital Hotel",
    address: "Bole Sub-city, Cameroon Street, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.021, lng: 38.771 },
    bannerImage:
      "https://images.unsplash.com/photo-1524175606-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1503676268-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529390078-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1523242940-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[2],
    ticketTiers: [
      {
        id: "tier_022",
        name: "Standard Ticket",
        price: 900,
        currency: "ETB",
        capacity: 40,
        sold: 18,
        description: "Full-day masterclass with playbook and templates.",
      },
      {
        id: "tier_023",
        name: "VIP Ticket",
        price: 1800,
        currency: "ETB",
        capacity: 15,
        sold: 6,
        description: "Includes lunch, one-on-one strategy session, and premium resources.",
      },
    ],
    ticketType: "paid",
    tags: ["digital marketing", "SEO", "social media", "advertising", "analytics"],
    isFeatured: false,
    views: 1300,
    registrations: 24,
    capacity: 55,
    createdAt: "2026-05-05T08:00:00+03:00",
  },
  {
    id: "evt_014",
    slug: "community-clean-up-drive",
    title: "Community Clean-Up Drive",
    description:
      "<p>Join your neighbors and fellow citizens for the Community Clean-Up Drive at Kolfe Park in Kolfe Keranio, a grassroots initiative aimed at improving the cleanliness and green spaces of Addis Ababa one neighborhood at a time. This free community event welcomes volunteers of all ages and abilities to contribute to a cleaner, healthier city.</p><p>Activities include waste collection and sorting, tree planting, painting of public benches and railings, and educational sessions on waste management and recycling. The event kicks off with a brief orientation and distribution of gloves, bags, and tools, followed by organized clean-up teams covering different zones of the park and surrounding streets.</p><p>Throughout the day, volunteers can participate in workshops on composting, upcycling, and reducing single-use plastics. Local environmental organizations will share information about ongoing sustainability projects and how residents can get more involved in environmental stewardship.</p><p>The drive concludes with a community gathering featuring refreshments, music, and recognition of outstanding volunteers. Together, we can make a visible difference in our community while building stronger neighborhood connections.</p>",
    shortDescription:
      "A community volunteer event for cleaning and greening Kolfe Park with waste collection, tree planting, and workshops.",
    category: categories[7],
    type: "meetup",
    status: "pending",
    date: "2026-06-14T00:00:00+03:00",
    endDate: "2026-06-15T00:00:00+03:00",
    time: "8:00 AM",
    endTime: "1:00 PM",
    location: "Kolfe Park",
    address: "Kolfe Keranio Sub-city, near Kolfe Bus Terminal, Addis Ababa",
    subCity: "Kolfe Keranio",
    coordinates: { lat: 9.0, lng: 38.71 },
    bannerImage:
      "https://images.unsplash.com/photo-1517486802-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1559028020-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1469573963-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529155467-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[3],
    ticketTiers: [
      {
        id: "tier_024",
        name: "Volunteer",
        price: 0,
        currency: "ETB",
        capacity: 200,
        sold: 45,
        description: "Free participation with gloves, bags, and refreshments provided.",
      },
    ],
    ticketType: "free",
    tags: ["community", "clean-up", "environment", "volunteer", "sustainability"],
    isFeatured: false,
    views: 800,
    registrations: 45,
    capacity: 200,
    createdAt: "2026-05-06T14:00:00+03:00",
  },
  {
    id: "evt_015",
    slug: "ai-and-machine-learning-conference",
    title: "AI & Machine Learning Conference",
    description:
      "<p>The AI & Machine Learning Conference at Skylight Hotel in Bole is Ethiopia's premier gathering for artificial intelligence researchers, practitioners, and enthusiasts. This two-day conference features cutting-edge research presentations, practical workshops, and panel discussions exploring the latest advances in machine learning, natural language processing, computer vision, and robotics.</p><p>The program includes keynote addresses from internationally recognized AI researchers, paper presentations from Ethiopian and African academics, and hands-on tutorials covering deep learning frameworks, model deployment, and ethical AI development. Special tracks focus on AI applications in healthcare, agriculture, financial services, and education relevant to the African context.</p><p>A dedicated startup pavilion showcases Ethiopian AI ventures, providing a platform for founders to demonstrate their solutions to potential investors and enterprise customers. The conference also hosts a hackathon where teams compete to solve real-world challenges using machine learning.</p><p>Networking sessions, poster presentations, and an industry exhibition round out the program, ensuring attendees leave with new knowledge, connections, and inspiration to advance AI innovation in Ethiopia and beyond.</p>",
    shortDescription:
      "Ethiopia's leading AI conference with research talks, workshops, a hackathon, and startup showcase.",
    category: categories[0],
    type: "conference",
    status: "approved",
    date: "2026-07-08T00:00:00+03:00",
    endDate: "2026-07-09T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "6:00 PM",
    location: "Skylight Hotel",
    address: "Bole Sub-city, Airport Road, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.026, lng: 38.782 },
    bannerImage:
      "https://images.unsplash.com/photo-1517245385279-89a33b0d3f0f?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505375081540-2a25c2d9d1e4?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[4],
    ticketTiers: [
      {
        id: "tier_025",
        name: "Standard Pass",
        price: 700,
        currency: "ETB",
        capacity: 400,
        sold: 134,
        description: "Full access to all sessions, workshops, and exhibition area.",
      },
      {
        id: "tier_026",
        name: "Academic Pass",
        price: 350,
        currency: "ETB",
        capacity: 150,
        sold: 72,
        description: "Discounted pass for students and faculty with valid ID.",
      },
      {
        id: "tier_027",
        name: "VIP Pass",
        price: 2000,
        currency: "ETB",
        capacity: 80,
        sold: 31,
        description: "VIP seating, exclusive dinner with speakers, and premium swag.",
      },
    ],
    ticketType: "paid",
    tags: ["AI", "machine learning", "deep learning", "conference", "research"],
    isFeatured: false,
    views: 2800,
    registrations: 237,
    capacity: 630,
    createdAt: "2026-05-08T09:00:00+03:00",
  },
  {
    id: "evt_016",
    slug: "afrobeats-night-live",
    title: "Afrobeats Night Live",
    description:
      "<p>Get ready for an electrifying night of Afrobeats at Gaslight Lounge in Bole, where the hottest sounds from Nigeria, Ghana, and Ethiopia's own vibrant music scene come together for an unforgettable live concert experience. Afrobeats Night Live brings together top DJs, live percussionists, and special guest vocalists for a high-energy celebration of Africa's dominant sound.</p><p>The venue's state-of-the-art sound system and dynamic lighting create the perfect atmosphere for dancing the night away. The evening opens with a set from a rising Ethiopian Afrobeats artist, followed by headline performances that blend Afrobeat, Amapiano, and Ethio-jazz influences into an irresistible groove.</p><p>Signature cocktails inspired by African flavors—think hibiscus mojitos, tej-based mixes, and mango margaritas—are available from the bar throughout the night. VIP tables offer bottle service and dedicated waitstaff for those seeking a premium experience.</p><p>Afrobeats Night Live is more than a concert—it is a cultural celebration connecting Addis Ababa to the broader Afrobeats movement sweeping the continent and the world.</p>",
    shortDescription:
      "A high-energy Afrobeats concert at Gaslight Lounge featuring top DJs, live percussion, and guest vocalists.",
    category: categories[5],
    type: "concert",
    status: "approved",
    date: "2026-06-19T00:00:00+03:00",
    endDate: "2026-06-20T00:00:00+03:00",
    time: "9:00 PM",
    endTime: "2:00 AM",
    location: "Gaslight Lounge",
    address: "Bole Sub-city, near Bole Medhanealem Church, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.023, lng: 38.774 },
    bannerImage:
      "https://images.unsplash.com/photo-1493221031-3b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1511678652744-4b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1492680515-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1516450360-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[5],
    ticketTiers: [
      {
        id: "tier_028",
        name: "General Admission",
        price: 300,
        currency: "ETB",
        capacity: 200,
        sold: 88,
        description: "Standard entry with dance floor access.",
      },
      {
        id: "tier_029",
        name: "VIP Table (4 pax)",
        price: 2000,
        currency: "ETB",
        capacity: 40,
        sold: 14,
        description: "Premium table for four with bottle service.",
      },
    ],
    ticketType: "paid",
    tags: ["afrobeats", "concert", "live music", "nightlife", "African music"],
    isFeatured: false,
    views: 1900,
    registrations: 102,
    capacity: 240,
    createdAt: "2026-05-09T16:00:00+03:00",
  },
  {
    id: "evt_017",
    slug: "sustainable-business-summit",
    title: "Sustainable Business Summit",
    description:
      "<p>The Sustainable Business Summit at Hilton Addis in Kirkos brings together corporate leaders, sustainability officers, policymakers, and environmental advocates to explore how businesses in Ethiopia can align profitability with environmental and social responsibility. This two-day conference addresses the urgent need for sustainable business practices in the context of Ethiopia's rapid economic growth.</p><p>The agenda covers ESG reporting standards, green supply chain management, renewable energy adoption, circular economy principles, and social impact measurement. International frameworks like the UN Sustainable Development Goals and the Task Force on Climate-related Financial Disclosures are examined through the lens of Ethiopian business realities.</p><p>Case studies from Ethiopian companies that have successfully implemented sustainability initiatives provide practical models for attendees. Breakout sessions enable deep dives into sector-specific challenges and opportunities, with tracks for manufacturing, agriculture, financial services, and technology.</p><p>The summit concludes with the signing of the Addis Sustainability Pledge, committing participating organizations to measurable sustainability targets. Networking sessions throughout the event facilitate cross-sector collaboration and partnership building.</p>",
    shortDescription:
      "A conference on sustainable business practices, ESG reporting, and green innovation in Ethiopia.",
    category: categories[1],
    type: "conference",
    status: "approved",
    date: "2026-07-12T00:00:00+03:00",
    endDate: "2026-07-13T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:30 PM",
    location: "Hilton Addis",
    address: "Kirkos Sub-city, Menelik II Avenue, Addis Ababa",
    subCity: "Kirkos",
    coordinates: { lat: 9.018, lng: 38.752 },
    bannerImage:
      "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1556765909-7e9c2e9b8c1b?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559131497-34a8a3f8b1b2?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600880292289-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[6],
    ticketTiers: [
      {
        id: "tier_030",
        name: "Standard Pass",
        price: 800,
        currency: "ETB",
        capacity: 250,
        sold: 78,
        description: "Full access to all sessions and networking events.",
      },
      {
        id: "tier_031",
        name: "Premium Pass",
        price: 2500,
        currency: "ETB",
        capacity: 60,
        sold: 22,
        description: "Premium seating, executive networking dinner, and sustainability toolkit.",
      },
    ],
    ticketType: "paid",
    tags: ["sustainability", "business", "ESG", "green", "corporate"],
    isFeatured: false,
    views: 1100,
    registrations: 100,
    capacity: 310,
    createdAt: "2026-05-10T10:00:00+03:00",
  },
  {
    id: "evt_018",
    slug: "traditional-medicine-workshop",
    title: "Traditional Medicine Workshop",
    description:
      "<p>The Traditional Medicine Workshop at Arada Heritage offers a unique opportunity to explore Ethiopia's rich heritage of indigenous healing practices. This free workshop is led by respected traditional healers and herbalists who share their knowledge of medicinal plants, diagnostic techniques, and holistic treatment approaches that have been passed down through generations.</p><p>Participants will learn to identify and use common medicinal herbs found in Ethiopia, understand the principles of traditional Ethiopian medicine including the role of spiritual and communal healing, and explore how traditional practices can complement modern healthcare. The workshop includes a guided tour of a traditional medicine garden and demonstrations of remedy preparation.</p><p>The program emphasizes the importance of preserving indigenous knowledge while promoting safe and responsible use of traditional remedies. Discussions address the integration of traditional and modern medicine, regulatory considerations, and the role of traditional healers in community health systems.</p><p>This workshop is part of a broader effort to document and revitalize Ethiopia's traditional medical knowledge, which faces threats from urbanization, environmental change, and the loss of oral traditions.</p>",
    shortDescription:
      "A free workshop exploring Ethiopian traditional healing practices, medicinal plants, and holistic wellness approaches.",
    category: categories[3],
    type: "workshop",
    status: "pending",
    date: "2026-06-26T00:00:00+03:00",
    endDate: "2026-06-27T00:00:00+03:00",
    time: "10:00 AM",
    endTime: "4:00 PM",
    location: "Arada Heritage",
    address: "Arada Sub-city, near St. George Cathedral, Addis Ababa",
    subCity: "Arada",
    coordinates: { lat: 9.042, lng: 38.738 },
    bannerImage:
      "https://images.unsplash.com/photo-1518616255-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544367567-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545205597-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545383165-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[7],
    ticketTiers: [
      {
        id: "tier_032",
        name: "Free Participation",
        price: 0,
        currency: "ETB",
        capacity: 50,
        sold: 20,
        description: "Free workshop including materials and herbal samples.",
      },
    ],
    ticketType: "free",
    tags: ["traditional medicine", "herbal", "wellness", "culture", "health"],
    isFeatured: false,
    views: 600,
    registrations: 20,
    capacity: 50,
    createdAt: "2026-05-11T12:00:00+03:00",
  },
  {
    id: "evt_019",
    slug: "photography-walk-old-addis",
    title: "Photography Walk: Old Addis",
    description:
      "<p>Capture the soul of Addis Ababa through your lens on the Photography Walk: Old Addis, a free guided walking tour through the historic streets of the Piazza District in Arada. This meetup is designed for photographers of all skill levels, from smartphone shooters to DSLR enthusiasts, who want to document the architectural and cultural heritage of Ethiopia's capital.</p><p>The walk covers iconic locations including the old railway station, Italian-era buildings, traditional markets, and hidden courtyards that tell the story of Addis Ababa's evolution from a small imperial camp to a bustling modern metropolis. Our guide, a professional photographer and historian, provides tips on composition, lighting, and street photography techniques while sharing fascinating historical context.</p><p>Participants are encouraged to share their work in a group chat after the walk, with the best photos featured in an online gallery and potentially in a future exhibition. The relaxed pace allows plenty of time for setting up shots, experimenting with different perspectives, and engaging with local residents and shopkeepers whose stories add depth to the images.</p><p>Bring your camera, comfortable walking shoes, and a sense of curiosity. All levels are welcome, and no prior photography experience is required.</p>",
    shortDescription:
      "A free guided photography walk through historic Piazza District, suitable for all skill levels.",
    category: categories[2],
    type: "meetup",
    status: "pending",
    date: "2026-06-10T00:00:00+03:00",
    endDate: "2026-06-11T00:00:00+03:00",
    time: "8:00 AM",
    endTime: "12:00 PM",
    location: "Piazza District",
    address: "Piazza, Arada Sub-city, Addis Ababa",
    subCity: "Arada",
    coordinates: { lat: 9.04, lng: 38.74 },
    bannerImage:
      "https://images.unsplash.com/photo-1513364776144-7b8b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1531912383-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1499898847-4b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1460664377893-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[8],
    ticketTiers: [
      {
        id: "tier_033",
        name: "Free Participant",
        price: 0,
        currency: "ETB",
        capacity: 30,
        sold: 14,
        description: "Free guided photography walk with tips and historical insights.",
      },
    ],
    ticketType: "free",
    tags: ["photography", "walk", "history", "architecture", "culture"],
    isFeatured: false,
    views: 750,
    registrations: 14,
    capacity: 30,
    createdAt: "2026-05-12T09:00:00+03:00",
  },
  {
    id: "evt_020",
    slug: "react-and-nextjs-workshop",
    title: "React & Next.js Workshop",
    description:
      "<p>The React & Next.js Workshop at Ice Addis in Bole is a hands-on, project-based training session for web developers who want to master modern frontend development with the React ecosystem. Over two intensive days, participants will build a full-featured web application using React 19, Next.js 15, TypeScript, and Tailwind CSS.</p><p>The curriculum covers component architecture, state management, server-side rendering, API routes, authentication, database integration with Prisma, and deployment to Vercel. Each concept is introduced through live coding sessions followed by independent practice exercises, ensuring that participants develop both understanding and muscle memory.</p><p>Instructors are senior frontend engineers with experience building production applications for Ethiopian and international companies. The workshop emphasizes best practices including performance optimization, accessibility, testing, and clean code principles. Real-world examples from Ethiopian tech companies provide relevant context.</p><p>By the end of the workshop, each participant will have deployed a live web application and gained the confidence to build modern, scalable frontends with React and Next.js. Lunch and refreshments are provided both days.</p>",
    shortDescription:
      "A hands-on two-day workshop building modern web apps with React 19, Next.js 15, TypeScript, and Tailwind CSS.",
    category: categories[0],
    type: "training",
    status: "approved",
    date: "2026-07-01T00:00:00+03:00",
    endDate: "2026-07-02T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:00 PM",
    location: "Ice Addis",
    address: "Bole Sub-city, near Dembel City Center, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.018, lng: 38.768 },
    bannerImage:
      "https://images.unsplash.com/photo-1517245385279-89a33b0d3f0f?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505375081540-2a25c2d9d1e4?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[9],
    ticketTiers: [
      {
        id: "tier_034",
        name: "Standard Registration",
        price: 1500,
        currency: "ETB",
        capacity: 40,
        sold: 16,
        description: "Two-day workshop with lunch, materials, and certificate.",
      },
      {
        id: "tier_035",
        name: "Premium Registration",
        price: 3000,
        currency: "ETB",
        capacity: 15,
        sold: 5,
        description: "Includes one-on-one mentoring session and early access to future workshops.",
      },
    ],
    ticketType: "paid",
    tags: ["React", "Next.js", "TypeScript", "web development", "frontend"],
    isFeatured: false,
    views: 1400,
    registrations: 21,
    capacity: 55,
    createdAt: "2026-05-13T10:00:00+03:00",
  },
  {
    id: "evt_021",
    slug: "networking-brunch-for-founders",
    title: "Networking Brunch for Founders",
    description:
      "<p>The Networking Brunch for Founders at Garden of Coffee in Bole brings together startup founders, co-founders, and solo entrepreneurs for a relaxed yet purposeful morning of connection and collaboration. Set in the lush garden of one of Bole's most charming venues, this brunch is designed to foster authentic relationships within Addis Ababa's entrepreneurial community.</p><p>The format is intentionally unstructured to encourage organic conversations. Upon arrival, founders receive a name tag and conversation starters. A curated seating arrangement ensures that each table mixes founders from different sectors—tech, agriculture, creative industries, and services—to maximize cross-pollination of ideas.</p><p>A light brunch featuring fresh juices, Ethiopian coffee, pastries, and traditional breakfast items is served throughout the morning. A brief welcome address highlights recent ecosystem developments and upcoming opportunities, but the majority of the time is dedicated to free-form networking.</p><p>Attendees are encouraged to share their current challenges and wins, seek advice from peers, and explore potential collaborations. Many partnerships, mentorships, and friendships have begun at these brunches, making them a staple of Addis Ababa's founder community.</p>",
    shortDescription:
      "A relaxed networking brunch for startup founders at Garden of Coffee, fostering connections and collaboration.",
    category: categories[1],
    type: "networking",
    status: "approved",
    date: "2026-06-16T00:00:00+03:00",
    endDate: "2026-06-17T00:00:00+03:00",
    time: "10:00 AM",
    endTime: "1:00 PM",
    location: "Garden of Coffee",
    address: "Bole Sub-city, Rwanda Street, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.02, lng: 38.77 },
    bannerImage:
      "https://images.unsplash.com/photo-1556765909-7e9c2e9b8c1b?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559131497-34a8a3f8b1b2?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600880292289-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[0],
    ticketTiers: [
      {
        id: "tier_036",
        name: "Founder Ticket",
        price: 350,
        currency: "ETB",
        capacity: 40,
        sold: 22,
        description: "Brunch and full networking experience.",
      },
      {
        id: "tier_037",
        name: "Founder+Guest",
        price: 600,
        currency: "ETB",
        capacity: 20,
        sold: 8,
        description: "Ticket for founder plus one guest.",
      },
    ],
    ticketType: "paid",
    tags: ["networking", "founders", "startups", "entrepreneurship", "brunch"],
    isFeatured: false,
    views: 950,
    registrations: 30,
    capacity: 60,
    createdAt: "2026-05-14T08:00:00+03:00",
  },
  {
    id: "evt_022",
    slug: "kids-coding-camp",
    title: "Kids Coding Camp",
    description:
      "<p>The Kids Coding Camp at Yeka Tech Hub offers an exciting introduction to computer programming for children aged 8-14. This week-long camp combines fun, creativity, and learning as young participants discover the power of coding through games, animations, and hands-on projects designed specifically for their age group.</p><p>The curriculum begins with visual programming using Scratch, where kids create their own interactive stories and games. As the week progresses, they advance to text-based coding with Python, building simple applications and learning computational thinking concepts that form the foundation of all programming languages.</p><p>Beyond coding, the camp includes activities that develop problem-solving skills, logical reasoning, creativity, and teamwork. Each day features a mix of structured lessons, free exploration time, and collaborative projects. Guest speakers from Ethiopia's tech industry share inspiring stories about careers in technology.</p><p>At the end of the camp, each child presents a project to parents and peers at a demo day celebration. All participants receive a certificate of completion and access to online resources to continue their coding journey at home.</p>",
    shortDescription:
      "A week-long coding camp for children aged 8-14, teaching programming through games, animations, and creative projects.",
    category: categories[4],
    type: "training",
    status: "approved",
    date: "2026-07-07T00:00:00+03:00",
    endDate: "2026-07-11T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "3:00 PM",
    location: "Yeka Tech Hub",
    address: "Yeka Sub-city, near Yeka Abado, Addis Ababa",
    subCity: "Yeka",
    coordinates: { lat: 9.038, lng: 38.788 },
    bannerImage:
      "https://images.unsplash.com/photo-1524175606-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1523242940-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1503676268-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529390078-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[1],
    ticketTiers: [
      {
        id: "tier_038",
        name: "Standard Camp Fee",
        price: 2000,
        currency: "ETB",
        capacity: 30,
        sold: 12,
        description: "Full week camp including materials, snacks, and certificate.",
      },
      {
        id: "tier_039",
        name: "Camp + Extended Care",
        price: 2800,
        currency: "ETB",
        capacity: 15,
        sold: 5,
        description: "Includes early drop-off and late pick-up options.",
      },
    ],
    ticketType: "paid",
    tags: ["kids", "coding", "education", "STEM", "summer camp"],
    isFeatured: false,
    views: 1700,
    registrations: 17,
    capacity: 45,
    createdAt: "2026-05-14T12:00:00+03:00",
  },
  {
    id: "evt_023",
    slug: "addis-marathon-prep-run",
    title: "Addis Marathon Prep Run",
    description:
      "<p>Join fellow runners for the Addis Marathon Prep Run, a free weekly group training session at Bole Atlas designed to help runners of all levels prepare for the annual Addis Ababa Marathon. Whether you are training for your first 5K or aiming for a personal best in the full marathon, this supportive community run will help you build endurance, improve your pace, and stay motivated.</p><p>Each session begins with a group warm-up and stretching led by a certified running coach. Participants then split into pace groups for runs ranging from 5 to 21 kilometers along a scenic route through Bole's tree-lined streets. Water stations are provided along the route, and the session concludes with guided cool-down stretches and recovery tips.</p><p>The Prep Run is more than just training—it is a community of runners who support each other's goals. Experienced marathoners share advice on nutrition, hydration, injury prevention, and race-day strategy. First-time runners receive extra encouragement and guidance to build confidence.</p><p>All fitness levels are welcome. No registration fee, no membership required—just show up with your running shoes and a positive attitude.</p>",
    shortDescription:
      "A free weekly group training run at Bole Atlas for marathon preparation, all fitness levels welcome.",
    category: categories[3],
    type: "meetup",
    status: "pending",
    date: "2026-06-09T00:00:00+03:00",
    endDate: "2026-06-10T00:00:00+03:00",
    time: "6:00 AM",
    endTime: "8:00 AM",
    location: "Bole Atlas",
    address: "Bole Sub-city, Atlas Area near Wossen Bakery, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.016, lng: 38.765 },
    bannerImage:
      "https://images.unsplash.com/photo-1544367567-9b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1518616255-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545205597-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545383165-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[2],
    ticketTiers: [
      {
        id: "tier_040",
        name: "Free Runner",
        price: 0,
        currency: "ETB",
        capacity: 100,
        sold: 35,
        description: "Free participation with coaching and water stations.",
      },
    ],
    ticketType: "free",
    tags: ["running", "marathon", "fitness", "health", "community"],
    isFeatured: false,
    views: 900,
    registrations: 35,
    capacity: 100,
    createdAt: "2026-05-15T06:00:00+03:00",
  },
  {
    id: "evt_024",
    slug: "poetry-open-mic-night",
    title: "Poetry Open Mic Night",
    description:
      "<p>Step up to the microphone at the Poetry Open Mic Night at Book Café in Arada, a free monthly gathering where poets, spoken word artists, and lovers of language come together to celebrate the power of words. Set in the cozy, book-lined atmosphere of one of Addis Ababa's most beloved independent bookshops, this event provides a supportive platform for both emerging and established voices.</p><p>The evening is open to all forms of poetic expression—classical verse, contemporary spoken word, Amharic poetry, English pieces, and bilingual performances. Each performer gets 5-7 minutes to share their work, with sign-ups available at the door. A featured headliner performs a longer set to open or close the night.</p><p>Beyond the performances, the open mic fosters a warm community where poets receive constructive feedback, discover collaborators for future projects, and find inspiration in each other's work. The café serves tea, coffee, and light refreshments throughout the evening.</p><p>Whether you have been writing poetry for years or are sharing your work for the first time, the Poetry Open Mic Night offers a welcoming space to express yourself and connect with Addis Ababa's vibrant literary community.</p>",
    shortDescription:
      "A free monthly open mic night for poets and spoken word artists at Book Café in Arada.",
    category: categories[2],
    type: "concert",
    status: "pending",
    date: "2026-06-21T00:00:00+03:00",
    endDate: "2026-06-22T00:00:00+03:00",
    time: "6:00 PM",
    endTime: "9:00 PM",
    location: "Book Café",
    address: "Arada Sub-city, near St. George Cathedral, Addis Ababa",
    subCity: "Arada",
    coordinates: { lat: 9.041, lng: 38.736 },
    bannerImage:
      "https://images.unsplash.com/photo-1499898847-4b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1460664377893-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1513364776144-7b8b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1531912383-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[3],
    ticketTiers: [
      {
        id: "tier_041",
        name: "Free Entry",
        price: 0,
        currency: "ETB",
        capacity: 60,
        sold: 25,
        description: "Free access to all performances and open mic participation.",
      },
    ],
    ticketType: "free",
    tags: ["poetry", "open mic", "spoken word", "literature", "culture"],
    isFeatured: false,
    views: 550,
    registrations: 25,
    capacity: 60,
    createdAt: "2026-05-15T14:00:00+03:00",
  },
  {
    id: "evt_025",
    slug: "fintech-innovation-day",
    title: "Fintech Innovation Day",
    description:
      "<p>Fintech Innovation Day at Radisson Blu in Bole is a premier gathering for financial technology leaders, banking executives, regulators, and innovators shaping the future of finance in Ethiopia. As the country undergoes rapid financial sector liberalization and digital transformation, this seminar provides essential insights into the opportunities and challenges ahead.</p><p>The agenda covers mobile money evolution, open banking APIs, digital lending, insurtech, blockchain-based financial services, and the regulatory landscape shaped by the National Bank of Ethiopia. Case studies from Kenya's M-Pesa, Nigeria's Paystack, and Ethiopia's own emerging fintech ecosystem provide practical lessons.</p><p>Breakout sessions allow deep dives into specific topics: merchant payment infrastructure, remittance corridors, agricultural finance technology, and financial inclusion for unbanked populations. A startup demo session features Ethiopian fintech companies presenting their solutions to a panel of investors and financial institution executives.</p><p>The day concludes with a networking reception where participants can continue conversations, explore partnerships, and exchange ideas about building a more inclusive and innovative financial system for Ethiopia.</p>",
    shortDescription:
      "A seminar on fintech innovation in Ethiopia featuring mobile money, digital lending, and regulatory insights.",
    category: categories[0],
    type: "seminar",
    status: "approved",
    date: "2026-07-15T00:00:00+03:00",
    endDate: "2026-07-16T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "5:00 PM",
    location: "Radisson Blu",
    address: "Bole Sub-city, Rwanda Street, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.021, lng: 38.773 },
    bannerImage:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1517245385279-89a33b0d3f0f?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505375081540-2a25c2d9d1e4?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[4],
    ticketTiers: [
      {
        id: "tier_042",
        name: "Standard Pass",
        price: 600,
        currency: "ETB",
        capacity: 250,
        sold: 88,
        description: "Full access to all sessions, demos, and networking reception.",
      },
      {
        id: "tier_043",
        name: "Premium Pass",
        price: 2000,
        currency: "ETB",
        capacity: 50,
        sold: 18,
        description: "Includes private lunch with speakers and exclusive networking.",
      },
    ],
    ticketType: "paid",
    tags: ["fintech", "digital banking", "mobile money", "innovation", "finance"],
    isFeatured: false,
    views: 2000,
    registrations: 106,
    capacity: 300,
    createdAt: "2026-05-16T10:00:00+03:00",
  },
  {
    id: "evt_026",
    slug: "ethiopian-wine-tasting",
    title: "Ethiopian Wine Tasting",
    description:
      "<p>Discover the emerging world of Ethiopian wine at the Ethiopian Wine Tasting event, hosted at the elegant Wine House in Bole. This guided tasting experience showcases wines from Ethiopia's pioneering vineyards, including the high-altitude estates of the Rift Valley and the emerging wine regions of the southern highlands.</p><p>Led by a certified sommelier with deep knowledge of Ethiopian viticulture, the tasting covers six to eight wines spanning white, rosé, and red varieties. Participants learn about the unique terroir of Ethiopian wine regions, the grape varieties being cultivated, and the winemaking techniques that are putting Ethiopian wine on the global map.</p><p>The tasting is paired with a selection of artisanal cheeses, cured meats, dried fruits, and traditional Ethiopian snacks designed to complement the wines. The sommelier guides participants through proper tasting techniques, flavor identification, and food pairing principles that can be applied beyond the event.</p><p>Whether you are a wine connoisseur or a curious beginner, this tasting offers a fascinating glimpse into Ethiopia's wine renaissance and a chance to taste wines that are rarely available outside the country.</p>",
    shortDescription:
      "A guided wine tasting featuring Ethiopian wines from Rift Valley vineyards, paired with artisanal cheeses and snacks.",
    category: categories[6],
    type: "workshop",
    status: "approved",
    date: "2026-06-27T00:00:00+03:00",
    endDate: "2026-06-28T00:00:00+03:00",
    time: "5:00 PM",
    endTime: "8:00 PM",
    location: "Wine House",
    address: "Bole Sub-city, near Bole Cinema, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.019, lng: 38.77 },
    bannerImage:
      "https://images.unsplash.com/photo-1504672446908-7d8e5c1b3b2b?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1414239778000-5d3b9c3a5b3f?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556909111-44e7e7a4b1b2?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505253049-5f0d9b2f6c1a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[5],
    ticketTiers: [
      {
        id: "tier_044",
        name: "Standard Tasting",
        price: 600,
        currency: "ETB",
        capacity: 40,
        sold: 18,
        description: "Guided tasting of 6 wines with food pairings.",
      },
      {
        id: "tier_045",
        name: "Premium Tasting",
        price: 1200,
        currency: "ETB",
        capacity: 20,
        sold: 7,
        description: "Includes reserve wine tastings and a bottle to take home.",
      },
    ],
    ticketType: "paid",
    tags: ["wine", "tasting", "Ethiopian", "culinary", "workshop"],
    isFeatured: false,
    views: 850,
    registrations: 25,
    capacity: 60,
    createdAt: "2026-05-17T11:00:00+03:00",
  },
  {
    id: "evt_027",
    slug: "mental-health-awareness-walk",
    title: "Mental Health Awareness Walk",
    description:
      "<p>The Mental Health Awareness Walk at Unity Park in Kirkos is a free community event dedicated to breaking the stigma around mental health in Ethiopia. Participants gather for a morning walk through one of Addis Ababa's most beautiful public spaces, demonstrating solidarity with those affected by mental health conditions and advocating for better access to mental health services.</p><p>The event begins with a short address from mental health professionals and advocates who share information about common mental health challenges, available resources, and the importance of community support. Participants then embark on a guided walk through Unity Park's gardens and pathways, with informational stations along the route providing facts about mental health, self-care tips, and crisis helpline numbers.</p><p>Following the walk, there is a wellness fair featuring booths from mental health organizations, counseling services, support groups, and holistic wellness practitioners. Free screening for common mental health conditions is available on-site, along with resources for follow-up care.</p><p>By walking together, we send a powerful message that mental health matters, that help is available, and that no one has to face their struggles alone. Wear green, the international color of mental health awareness.</p>",
    shortDescription:
      "A free community walk at Unity Park raising awareness about mental health and reducing stigma in Ethiopia.",
    category: categories[3],
    type: "meetup",
    status: "pending",
    date: "2026-06-13T00:00:00+03:00",
    endDate: "2026-06-14T00:00:00+03:00",
    time: "7:00 AM",
    endTime: "11:00 AM",
    location: "Unity Park",
    address: "Kirkos Sub-city, near the National Palace, Addis Ababa",
    subCity: "Kirkos",
    coordinates: { lat: 9.022, lng: 38.748 },
    bannerImage:
      "https://images.unsplash.com/photo-1545205597-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544367567-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1518616255-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545383165-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[6],
    ticketTiers: [
      {
        id: "tier_046",
        name: "Free Participant",
        price: 0,
        currency: "ETB",
        capacity: 300,
        sold: 62,
        description: "Free community walk with wellness fair and resources.",
      },
    ],
    ticketType: "free",
    tags: ["mental health", "awareness", "walk", "wellness", "community"],
    isFeatured: false,
    views: 1200,
    registrations: 62,
    capacity: 300,
    createdAt: "2026-05-18T08:00:00+03:00",
  },
  {
    id: "evt_028",
    slug: "startup-legal-clinic",
    title: "Startup Legal Clinic",
    description:
      "<p>The Startup Legal Clinic at Getfam Hotel in Bole is a free consultation event that connects early-stage founders with experienced legal professionals who specialize in Ethiopian business law. Navigating the legal landscape is one of the biggest challenges for new businesses, and this clinic provides practical guidance on the legal foundations every startup needs.</p><p>Legal experts provide one-on-one consultations covering business registration and licensing, intellectual property protection, contract law, employment regulations, tax obligations, and fundraising documentation. Each session lasts 30 minutes and is tailored to the specific needs of the startup.</p><p>In addition to individual consultations, the clinic features short presentations on pressing legal topics for startups: choosing the right legal structure, understanding shareholder agreements, navigating Ethiopia's investment proclamation, and protecting your brand through trademark registration. Q&A sessions follow each presentation.</p><p>Attendees leave with actionable checklists, template documents, and a clearer understanding of their legal responsibilities and options. The clinic is conducted in both Amharic and English to ensure accessibility for all founders.</p>",
    shortDescription:
      "A free legal clinic for startups offering one-on-one consultations with business law experts at Getfam Hotel.",
    category: categories[1],
    type: "seminar",
    status: "pending",
    date: "2026-07-02T00:00:00+03:00",
    endDate: "2026-07-03T00:00:00+03:00",
    time: "10:00 AM",
    endTime: "4:00 PM",
    location: "Getfam Hotel",
    address: "Bole Sub-city, near Bole Bulbula, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.015, lng: 38.762 },
    bannerImage:
      "https://images.unsplash.com/photo-1556765909-7e9c2e9b8c1b?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559131497-34a8a3f8b1b2?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600880292289-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[7],
    ticketTiers: [
      {
        id: "tier_047",
        name: "Free Consultation",
        price: 0,
        currency: "ETB",
        capacity: 50,
        sold: 28,
        description: "Free 30-minute legal consultation with presentations and resources.",
      },
    ],
    ticketType: "free",
    tags: ["startups", "legal", "consultation", "entrepreneurship", "business"],
    isFeatured: false,
    views: 700,
    registrations: 28,
    capacity: 50,
    createdAt: "2026-05-19T09:00:00+03:00",
  },
  {
    id: "evt_029",
    slug: "dj-workshop-and-beatmaking",
    title: "DJ Workshop & Beatmaking",
    description:
      "<p>The DJ Workshop & Beatmaking session at Studio 26 in Bole offers aspiring DJs and music producers an immersive introduction to the art of electronic music creation. Held in a professional recording studio, this hands-on workshop covers the fundamentals of DJing, beat production, and live performance techniques.</p><p>Participants learn equipment setup, mixing techniques, beat matching, phrasing, and crowd reading from experienced DJs who have performed at major venues across Addis Ababa and beyond. The workshop provides hands-on time with professional-grade DJ controllers, turntables, and production software including Ableton Live and Serato.</p><p>The beatmaking segment dives into rhythm programming, melody creation, sampling, and arrangement. Participants create their own short tracks under the guidance of producers who blend traditional Ethiopian musical elements with modern electronic genres like house, techno, and hip-hop.</p><p>By the end of the workshop, each participant will have recorded a short mix or produced a basic beat, gaining the foundational skills needed to continue developing their craft independently.</p>",
    shortDescription:
      "A hands-on workshop on DJing and beat production at Studio 26, covering mixing, sampling, and music production.",
    category: categories[5],
    type: "workshop",
    status: "approved",
    date: "2026-06-24T00:00:00+03:00",
    endDate: "2026-06-25T00:00:00+03:00",
    time: "2:00 PM",
    endTime: "7:00 PM",
    location: "Studio 26",
    address: "Bole Sub-city, near Bole Airport, Addis Ababa",
    subCity: "Bole",
    coordinates: { lat: 9.027, lng: 38.781 },
    bannerImage:
      "https://images.unsplash.com/photo-1511678652744-4b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1493221031-3b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1492680515-9b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1516450360-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[8],
    ticketTiers: [
      {
        id: "tier_048",
        name: "Standard Ticket",
        price: 800,
        currency: "ETB",
        capacity: 20,
        sold: 9,
        description: "Full workshop with hands-on equipment access.",
      },
      {
        id: "tier_049",
        name: "Premium Ticket",
        price: 1500,
        currency: "ETB",
        capacity: 10,
        sold: 4,
        description: "Includes extended studio time and personalized feedback.",
      },
    ],
    ticketType: "paid",
    tags: ["DJ", "beatmaking", "music production", "workshop", "electronic music"],
    isFeatured: false,
    views: 650,
    registrations: 13,
    capacity: 30,
    createdAt: "2026-05-20T10:00:00+03:00",
  },
  {
    id: "evt_030",
    slug: "volunteer-training-program",
    title: "Volunteer Training Program",
    description:
      "<p>The Volunteer Training Program at Red Cross Center in Lideta is a free comprehensive training session for individuals interested in becoming effective volunteers for community service organizations across Addis Ababa. This full-day program equips participants with the knowledge, skills, and confidence needed to make meaningful contributions to volunteer initiatives.</p><p>The curriculum covers the principles of volunteerism, communication and interpersonal skills, cultural sensitivity, safety and first aid basics, project management for community initiatives, and understanding the ethical responsibilities of volunteers. Training is delivered through a mix of presentations, group discussions, role-playing exercises, and practical simulations.</p><p>Participants also learn about specific volunteer opportunities available through partner organizations including environmental clean-ups, youth mentoring programs, elderly care initiatives, health awareness campaigns, and disaster response preparedness. Representatives from these organizations are present to share information and recruit volunteers.</p><p>Upon completion, participants receive a certificate of training and are connected with volunteer opportunities that match their interests and availability. This program is ideal for anyone looking to give back to their community in a structured, impactful way.</p>",
    shortDescription:
      "A free training program for aspiring volunteers covering communication, first aid, and community service skills.",
    category: categories[7],
    type: "training",
    status: "pending",
    date: "2026-07-06T00:00:00+03:00",
    endDate: "2026-07-07T00:00:00+03:00",
    time: "9:00 AM",
    endTime: "4:00 PM",
    location: "Red Cross Center",
    address: "Lideta Sub-city, near Mexico Square, Addis Ababa",
    subCity: "Lideta",
    coordinates: { lat: 9.008, lng: 38.728 },
    bannerImage:
      "https://images.unsplash.com/photo-1469573963-8b1b4c1b3b2a?w=1200&h=600&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1517486802-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559028020-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529155467-8b1b4c1b3b2a?w=800&h=600&fit=crop&q=80",
    ],
    organizer: organizers[9],
    ticketTiers: [
      {
        id: "tier_050",
        name: "Free Training",
        price: 0,
        currency: "ETB",
        capacity: 80,
        sold: 38,
        description: "Free full-day training with materials, certificate, and lunch.",
      },
    ],
    ticketType: "free",
    tags: ["volunteer", "training", "community", "social impact", "capacity building"],
    isFeatured: false,
    views: 500,
    registrations: 38,
    capacity: 80,
    createdAt: "2026-05-21T09:00:00+03:00",
  },
];
