import { Organizer } from "../types";

export const organizers: Organizer[] = [
  { id: "org_001", name: "Addis Tech Hub", slug: "addis-tech-hub", email: "info@addistechhub.com", phone: "+251-911-123-456", avatar: "https://randomuser.me/api/portraits/men/32.jpg", bio: "Leading technology community in Addis Ababa organizing conferences, hackathons, and tech meetups.", website: "https://addistechhub.com", verified: true, eventsCount: 15, totalAttendees: 3200, joinedDate: "2024-01-15", socialLinks: { twitter: "@addistechhub", linkedin: "addis-tech-hub", instagram: "@addistechhub" } },
  { id: "org_002", name: "Ethiopian Business Forum", slug: "ethiopian-business-forum", email: "contact@ethiopianbusinessforum.com", phone: "+251-911-234-567", avatar: "https://randomuser.me/api/portraits/women/44.jpg", bio: "Bringing together entrepreneurs, investors, and business leaders to foster economic growth.", website: "https://ethiopianbusinessforum.com", verified: true, eventsCount: 12, totalAttendees: 2800, joinedDate: "2024-02-20", socialLinks: { twitter: "@ethbizforum", linkedin: "ethiopian-business-forum" } },
  { id: "org_003", name: "Meskel Cultural Foundation", slug: "meskel-cultural-foundation", email: "hello@meskelfoundation.org", phone: "+251-911-345-678", avatar: "https://randomuser.me/api/portraits/men/67.jpg", bio: "Preserving and promoting Ethiopian arts, culture, and heritage through events and exhibitions.", verified: true, eventsCount: 8, totalAttendees: 1500, joinedDate: "2024-03-10" },
  { id: "org_004", name: "Selam Wellness Center", slug: "selam-wellness", email: "info@selamwellness.com", phone: "+251-911-456-789", avatar: "https://randomuser.me/api/portraits/women/68.jpg", bio: "Holistic wellness center offering yoga, meditation, and health workshops in Addis Ababa.", website: "https://selamwellness.com", verified: false, eventsCount: 4, totalAttendees: 600, joinedDate: "2024-04-05" },
  { id: "org_005", name: "Habesha Innovators", slug: "habesha-innovators", email: "team@habeshainnovators.com", phone: "+251-911-567-890", avatar: "https://randomuser.me/api/portraits/men/45.jpg", bio: "A collective of Ethiopian innovators working on cutting-edge technology and social impact projects.", verified: true, eventsCount: 10, totalAttendees: 2100, joinedDate: "2024-01-28", socialLinks: { twitter: "@habeshainnovate", linkedin: "habesha-innovators", instagram: "@habeshainnovators" } },
  { id: "org_006", name: "Unity Training Institute", slug: "unity-training", email: "info@unitytraining.edu.et", phone: "+251-911-678-901", avatar: "https://randomuser.me/api/portraits/women/22.jpg", bio: "Professional training and certification institute offering courses in various fields.", verified: false, eventsCount: 6, totalAttendees: 900, joinedDate: "2024-05-12" },
  { id: "org_007", name: "Jazzamba Events", slug: "jazzamba-events", email: "bookings@jazzamba.com", phone: "+251-911-789-012", avatar: "https://randomuser.me/api/portraits/men/55.jpg", bio: "Addis Ababa's premier jazz and live music event organizer. Experience the best of Ethiopian and international jazz.", verified: true, eventsCount: 9, totalAttendees: 1800, joinedDate: "2024-02-14", socialLinks: { instagram: "@jazzambaaddis" } },
  { id: "org_008", name: "Green Ethiopia Foundation", slug: "green-ethiopia", email: "contact@greenethiopia.org", phone: "+251-911-890-123", avatar: "https://randomuser.me/api/portraits/women/33.jpg", bio: "Environmental conservation organization focused on reforestation and sustainable development.", website: "https://greenethiopia.org", verified: false, eventsCount: 3, totalAttendees: 450, joinedDate: "2024-06-01" },
  { id: "org_009", name: "Addis Eats Collective", slug: "addis-eats", email: "hello@addiseats.com", phone: "+251-911-901-234", avatar: "https://randomuser.me/api/portraits/men/78.jpg", bio: "Food lovers community organizing culinary events, food festivals, and cooking workshops across Addis.", verified: false, eventsCount: 5, totalAttendees: 750, joinedDate: "2024-03-22", socialLinks: { instagram: "@addiseats" } },
  { id: "org_010", name: "Women in Tech Ethiopia", slug: "women-in-tech-ethiopia", email: "info@womenintechethiopia.org", phone: "+251-911-012-345", avatar: "https://randomuser.me/api/portraits/women/56.jpg", bio: "Empowering women in technology through mentorship, workshops, and networking events.", website: "https://womenintechethiopia.org", verified: true, eventsCount: 7, totalAttendees: 1400, joinedDate: "2024-04-18", socialLinks: { twitter: "@womenintechet", linkedin: "women-in-tech-ethiopia", instagram: "@womenintechethiopia" } },
];
