// ============================================================================
// @eventology/config — Entity Configuration
// ============================================================================
// Single source of truth for how each entity is accessed, displayed, and
// queried. Factory hooks and API routes consume this config.
// ============================================================================

export const ENTITY_CONFIG = {
  profiles: {
    table: 'profiles',
    label: 'Profile',
    labelPlural: 'Profiles',
    searchFields: ['full_name', 'email'] as const,
    labelField: 'full_name',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: '/api/public/profiles',
    protectedPath: '/api/protected/profiles',
  },
  organizers: {
    table: 'organizers',
    label: 'Organizer',
    labelPlural: 'Organizers',
    searchFields: ['name', 'email', 'bio'] as const,
    labelField: 'name',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: '/api/public/organizers',
    protectedPath: '/api/protected/organizers',
  },
  categories: {
    table: 'categories',
    label: 'Category',
    labelPlural: 'Categories',
    searchFields: ['name', 'description'] as const,
    labelField: 'name',
    sortField: 'sort_order',
    sortOrder: 'asc' as const,
    publicPath: '/api/public/categories',
    protectedPath: '/api/protected/categories',
  },
  venues: {
    table: 'venues',
    label: 'Venue',
    labelPlural: 'Venues',
    searchFields: ['name', 'address', 'sub_city'] as const,
    labelField: 'name',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: '/api/public/venues',
    protectedPath: '/api/protected/venues',
  },
  events: {
    table: 'events',
    label: 'Event',
    labelPlural: 'Events',
    searchFields: ['title', 'description', 'short_description', 'venue_name', 'venue_address'] as const,
    labelField: 'title',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: '/api/public/events',
    protectedPath: '/api/protected/events',
  },
  ticket_tiers: {
    table: 'ticket_tiers',
    label: 'Ticket Tier',
    labelPlural: 'Ticket Tiers',
    searchFields: ['name', 'description'] as const,
    labelField: 'name',
    sortField: 'sort_order',
    sortOrder: 'asc' as const,
    publicPath: '/api/public/ticket-tiers',
    protectedPath: '/api/protected/ticket-tiers',
  },
  registrations: {
    table: 'registrations',
    label: 'Registration',
    labelPlural: 'Registrations',
    searchFields: ['attendee_name', 'attendee_email'] as const,
    labelField: 'attendee_name',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/registrations',
  },
  tickets: {
    table: 'tickets',
    label: 'Ticket',
    labelPlural: 'Tickets',
    searchFields: ['ticket_number', 'tier_name'] as const,
    labelField: 'ticket_number',
    sortField: 'issued_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/tickets',
  },
  payments: {
    table: 'payments',
    label: 'Payment',
    labelPlural: 'Payments',
    searchFields: ['notes'] as const,
    labelField: 'id',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/payments',
  },
  payouts: {
    table: 'payouts',
    label: 'Payout',
    labelPlural: 'Payouts',
    searchFields: ['notes'] as const,
    labelField: 'id',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/payouts',
  },
  conversations: {
    table: 'conversations',
    label: 'Conversation',
    labelPlural: 'Conversations',
    searchFields: ['subject'] as const,
    labelField: 'subject',
    sortField: 'last_message_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/conversations',
  },
  messages: {
    table: 'messages',
    label: 'Message',
    labelPlural: 'Messages',
    searchFields: ['content'] as const,
    labelField: 'content',
    sortField: 'created_at',
    sortOrder: 'asc' as const,
    publicPath: null,
    protectedPath: '/api/protected/messages',
  },
  reviews: {
    table: 'reviews',
    label: 'Review',
    labelPlural: 'Reviews',
    searchFields: ['title', 'content'] as const,
    labelField: 'title',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: '/api/public/reviews',
    protectedPath: '/api/protected/reviews',
  },
  sponsors: {
    table: 'sponsors',
    label: 'Sponsor',
    labelPlural: 'Sponsors',
    searchFields: ['name', 'description'] as const,
    labelField: 'name',
    sortField: 'sort_order',
    sortOrder: 'asc' as const,
    publicPath: '/api/public/sponsors',
    protectedPath: '/api/protected/sponsors',
  },
  notifications: {
    table: 'notifications',
    label: 'Notification',
    labelPlural: 'Notifications',
    searchFields: ['title', 'message'] as const,
    labelField: 'title',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/notifications',
  },
  event_views: {
    table: 'event_views',
    label: 'Event View',
    labelPlural: 'Event Views',
    searchFields: [] as const,
    labelField: 'id',
    sortField: 'viewed_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/event-views',
  },
  audit_log: {
    table: 'audit_log',
    label: 'Audit Log',
    labelPlural: 'Audit Log',
    searchFields: ['target_label', 'details'] as const,
    labelField: 'target_label',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/audit-log',
  },
  promo_codes: {
    table: 'promo_codes',
    label: 'Promo Code',
    labelPlural: 'Promo Codes',
    searchFields: ['code', 'description'] as const,
    labelField: 'code',
    sortField: 'created_at',
    sortOrder: 'desc' as const,
    publicPath: null,
    protectedPath: '/api/protected/promo-codes',
  },
} as const;

export type EntityKey = keyof typeof ENTITY_CONFIG;
