// ============================================================================
// @eventology/schemas — Event Zod Schemas
// Source: 006_events.sql
// ============================================================================

import { z } from 'zod';
import { EVENT_STATUSES, EVENT_TYPES, TICKET_TYPES } from '../enums';
import { pgUuid } from '../primitives';

// ---------------------------------------------------------------------------
// Base schema (matches DB constraints exactly)
// ---------------------------------------------------------------------------

export const eventSchema = z.object({
  id: z.string().uuid(),
  organizer_id: z.string().uuid(),
  category_id: z.string().uuid(),
  venue_id: z.string().uuid().nullable(),
  title: z.string().min(1, 'Title is required').max(255),
  slug: z
    .string()
    .min(1)
    .max(255)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Invalid slug format'),
  description: z.string().nullable(), // Rich text HTML
  short_description: z.string().max(500).nullable(),
  banner_image: z.string().url().nullable(),
  gallery: z.array(z.string().url()).default([]),
  event_type: z.enum(EVENT_TYPES),
  ticket_type: z.enum(TICKET_TYPES),
  tags: z.array(z.string()).default([]),
  start_date: z.string().datetime(),
  end_date: z.string().datetime(),
  timezone: z.string().default('Africa/Addis_Ababa'),
  venue_name: z.string().nullable(),
  venue_address: z.string().nullable(),
  sub_city: z.string().nullable(),
  latitude: z.number().min(-90).max(90).nullable(),
  longitude: z.number().min(-180).max(180).nullable(),
  location: z.unknown(), // PostGIS geometry
  status: z.enum(EVENT_STATUSES),
  rejection_reason: z.string().nullable(),
  is_featured: z.boolean(),
  featured_until: z.string().datetime().nullable(),
  capacity: z.number().int().min(0),
  registrations_count: z.number().int().min(0),
  views_count: z.number().int().min(0),
  metadata: z.record(z.string(), z.unknown()).default({}),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

// ---------------------------------------------------------------------------
// Create schema
// ---------------------------------------------------------------------------

export const createEventSchema = eventSchema
  .omit({
    id: true,
    organizer_id: true, // Server-injected from the caller's organizer profile
    location: true, // Auto-generated by trigger
    status: true, // Set by workflow
    rejection_reason: true,
    is_featured: true,
    featured_until: true,
    registrations_count: true,
    views_count: true,
    created_at: true,
    updated_at: true,
  })
  .extend({
    ticket_type: z.enum(TICKET_TYPES).default('free'),
    timezone: z.string().default('Africa/Addis_Ababa'),
    tags: z.array(z.string()).default([]),
    gallery: z.array(z.string().url()).default([]),
    capacity: z.number().int().min(0).default(0),
    metadata: z.record(z.string(), z.unknown()).default({}),
    // DB-sourced UUID — seed categories use version-0 IDs that Zod's
    // .uuid() rejects. Use pgUuid() (matches Postgres).
    category_id: pgUuid(),
    // venue_id is optional on create (form may omit it) — nullish so an
    // absent key is accepted (missing !== null in Zod).
    venue_id: pgUuid().nullish(),
    // Optional text/number fields the form sends as `undefined` (stripped
    // by JSON.stringify). .nullish() accepts both undefined and null.
    description: z.string().nullish(),
    short_description: z.string().max(500).nullish(),
    banner_image: z.string().url().nullish(),
    venue_name: z.string().nullish(),
    venue_address: z.string().nullish(),
    sub_city: z.string().nullish(),
    latitude: z.number().min(-90).max(90).nullish(),
    longitude: z.number().min(-180).max(180).nullish(),
    // Create-time only: draft (save) or pending (submit for review).
    // Server re-injects after stripping SERVER_CONTROLLED_FIELDS; never
    // accept approved/rejected/cancelled from the client.
    status: z.enum(['draft', 'pending']).optional().default('draft'),
  })
  .refine(
    (data) => new Date(data.end_date) > new Date(data.start_date),
    { message: 'End date must be after start date', path: ['end_date'] }
  );

// ---------------------------------------------------------------------------
// Update schema (all fields optional, no refinement — validated at route level)
// ---------------------------------------------------------------------------

export const updateEventSchema = z.object({
  organizer_id: pgUuid().optional(),
  category_id: pgUuid().optional(),
  venue_id: pgUuid().nullish(),
  title: z.string().min(1, 'Title is required').max(255).optional(),
  slug: z
    .string()
    .min(1)
    .max(255)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Invalid slug format')
    .optional(),
  description: z.string().nullable().optional(),
  short_description: z.string().max(500).nullable().optional(),
  banner_image: z.string().url().nullable().optional(),
  gallery: z.array(z.string().url()).optional(),
  event_type: z.enum(EVENT_TYPES).optional(),
  ticket_type: z.enum(TICKET_TYPES).optional(),
  tags: z.array(z.string()).optional(),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  timezone: z.string().optional(),
  venue_name: z.string().nullable().optional(),
  venue_address: z.string().nullable().optional(),
  sub_city: z.string().nullable().optional(),
  latitude: z.number().min(-90).max(90).nullable().optional(),
  longitude: z.number().min(-180).max(180).nullable().optional(),
  status: z.enum(EVENT_STATUSES).optional(),
  rejection_reason: z.string().nullable().optional(),
  is_featured: z.boolean().optional(),
  featured_until: z.string().datetime().nullable().optional(),
  capacity: z.number().int().min(0).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type EventFormData = z.infer<typeof createEventSchema>;
export type EventUpdateData = z.infer<typeof updateEventSchema>;

