// ============================================================================
// @eventology/schemas — Venue Zod Schemas
// Source: 005_categories_venues.sql
// ============================================================================

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Base schema (matches DB constraints exactly)
// ---------------------------------------------------------------------------

export const venueSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1, 'Venue name is required').max(255),
  slug: z
    .string()
    .min(1)
    .max(255)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Invalid slug format'),
  address: z.string().min(1, 'Address is required'),
  sub_city: z.string().min(1, 'Sub-city is required'),
  city: z.string().min(1).default('Addis Ababa'),
  country: z.string().min(1).default('Ethiopia'),
  latitude: z.number().min(-90).max(90).nullable(),
  longitude: z.number().min(-180).max(180).nullable(),
  location: z.unknown(), // PostGIS geometry — not validated at app level
  capacity: z.number().int().positive().nullable(),
  description: z.string().max(5000).nullable(),
  image_url: z.string().url().nullable(),
  amenities: z.array(z.string()).default([]),
  contact_phone: z.string().nullable(),
  contact_email: z.string().email().nullable(),
  is_active: z.boolean(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

// ---------------------------------------------------------------------------
// Create schema
// ---------------------------------------------------------------------------

export const createVenueSchema = venueSchema
  .omit({
    id: true,
    location: true, // Auto-generated by trigger from lat/lng
    created_at: true,
    updated_at: true,
  })
  .extend({
    city: z.string().min(1).default('Addis Ababa'),
    country: z.string().min(1).default('Ethiopia'),
    is_active: z.boolean().default(true),
    amenities: z.array(z.string()).default([]),
  });

// ---------------------------------------------------------------------------
// Update schema
// ---------------------------------------------------------------------------

export const updateVenueSchema = createVenueSchema.partial();

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type VenueFormData = z.infer<typeof createVenueSchema>;
export type VenueUpdateData = z.infer<typeof updateVenueSchema>;

